name: picsart_clone
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  rxdart: ^0.24.1
  flutter_colorpicker: ^0.3.4
  flutter_icons: ^1.1.0
  flutter_animated_dialog: ^1.1.0
  #image editor
  image: ^2.1.10
  image_picker: ^0.6.7
  image_cropper: ^1.3.1
  image_gallery_saver: ^1.5.0
  flutter_image: ^3.0.0
  photofilters: ^2.0.1
  multi_image_picker: ^4.7.13
#  image_collage_widget: ^0.0.1
  photo_view: ^0.10.2
  flutter_image_editor: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true